<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><ProjectReference Include="../Webspine.Rendering.Legacy/Webspine.Rendering.Legacy.csproj" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <ProjectReference Include="../Webspine.Core/Webspine.Core.csproj" />
  </ItemGroup>
</Project>
