<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../experiments/Webspine.RazorPrototype/Webspine.RazorPrototype.csproj" />
  </ItemGroup>
</Project>
