<Project Sdk="Microsoft.NET.Sdk.Razor">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Webspine.Rendering.Razor/Webspine.Rendering.Razor.csproj" />
    <EmbeddedResource Include="Assets/*" LogicalName="studio/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
