<?php
declare(strict_types=1);

// Plain text only. The theme escapes every value when rendering.
return [
    'the_field_guide' => 'THE FIELD GUIDE',
    'v' => '/ v',
    'understand_it' => 'Understand it.',
    'make_it_yours' => 'Make it yours.',
    'a_practical_guide_to_a_deliberately_small' => 'A practical guide to a deliberately small framework.',
    'find_in_this_guide' => 'Find in this guide',
    'placeholder_search_documentation' => 'Search documentation…',
    'aria_label_documentation_sections' => 'Documentation sections',
    'href_quickstart' => '#quickstart',
    '01_quick_start' => '01   Quick start',
    'href_principles' => '#principles',
    '02_principles' => '02   Principles',
    'href_architecture' => '#architecture',
    '03_architecture' => '03   Architecture',
    'href_configuration' => '#configuration',
    '04_configuration' => '04   Configuration',
    'href_themes' => '#themes',
    '05_themes' => '05   Themes',
    'href_plugins' => '#plugins',
    '06_plugins_services' => '06   Plugins & services',
    'href_updates' => '#updates',
    '07_core_updates' => '07   Core updates',
    'href_deployment' => '#deployment',
    '08_deployment' => '08   Deployment',
    'href_quality' => '#quality',
    '09_quality_security' => '09   Quality & security',
    'href_roadmap' => '#roadmap',
    '10_status_roadmap' => '10   Status & roadmap',
    'readable_by_humans' => 'Readable by humans.',
    'friendly_to_ai' => 'Friendly to AI.',
    '01_get_going' => '01 / GET GOING',
    'your_first_five_minutes' => 'Your first five minutes.',
    'download_the_bootstrap_zip_and_extract_it' => 'Download the bootstrap ZIP and extract it. You need',
    'php_8_3' => 'PHP 8.3+',
    'with' => 'with',
    'pdo_sqlite' => 'pdo_sqlite',
    'openssl' => 'openssl',
    'for_smtp_and' => 'for SMTP, and',
    'zip' => 'zip',
    'for_packaging_and_updates_no_composer_npm' => 'for packaging and updates. No Composer, npm, or build step.',
    'href_download' => '/download',
    'download_webspine_v' => 'Download webspine v',
    'copy' => 'Copy ⧉',
    'php_bin_console_php_install_php_bin' => 'php core/bin/console.php install
php core/bin/console.php health
php -S localhost:8080 -t public public/router.php',
    'visit' => 'Visit',
    'href_http_localhost_8080' => 'http://localhost:8080',
    'localhost_8080' => 'localhost:8080',
    'installation_explicitly_creates_sqlite_tables_records_schema' => '. Installation explicitly creates SQLite tables, records schema version 1, and selects the Studio theme. Re-running it preserves settings and pages. Requests never install or migrate a database.',
    'use_the_php_development_server_locally_in' => 'Use the PHP development server locally. In production, configure your web server with',
    'public' => 'public/',
    'as_its_only_document_root' => 'as its only document root.',
    '02_the_intent' => '02 / THE INTENT',
    'small_is_a_design_decision' => 'Small is a design decision.',
    'the_core_goal_of' => 'The core goal of',
    'is_to_let_you_build_extend_and' => 'is to let you build, extend, and maintain your own website entirely with AI. Familiar code, a readable structure, and explicit contracts give an AI contributor a project it can understand.',
    'bring_your_own_ai_app_with_access' => 'Bring your own AI app with access to the project files, such as ChatGPT Desktop, Claude Code, or OpenCode. The project stays independent of any AI vendor; you can also edit every file by hand.',
    'keep_the_core_small_and_understandable' => 'Keep the core small and understandable.',
    'keep_content_and_routes_in' => 'Keep content and routes in',
    'site' => 'site/',
    'presentation_in' => ', presentation in',
    'themes' => 'site/themes/',
    'and_capabilities_in' => ', and capabilities in',
    'plugins' => 'site/plugins/',
    'choose_providers_explicitly_avoid_hidden_configuration_in' => 'Choose providers explicitly. Avoid hidden configuration in the database.',
    'preserve_a_theme_s_identity_every_website' => 'Preserve a theme’s identity. Every website can look different.',
    'ai_contributors_should_inspect_existing_work_make' => 'AI contributors should inspect existing work, make scoped changes, run relevant checks, report gaps, and protect secrets.',
    '03_a_place_for_everything' => '03 / A PLACE FOR EVERYTHING',
    'one_project_clear_boundaries' => 'One project. Clear boundaries.',
    'core' => 'core/',
    'routing_contracts_registry_hooks_themes_and_updates' => 'Framework, bundled providers, tools, tests, and guides',
    'content_identity_page_titles_urls_and_starter' => 'Content, identity, page titles, URLs, and starter data',
    'templates_shared_layouts_scoped_css_and_browser' => 'Templates, shared layouts, scoped CSS, and browser JS',
    'provider_and_feature_extensions_with_manifests' => 'Provider and feature extensions with manifests',
    'config' => 'config/',
    'private_provider_selection_and_credentials' => 'Private provider selection and credentials',
    'storage' => 'storage/',
    'sqlite_update_stages_backups_and_locks' => 'SQLite, update stages, backups, and locks',
    'the_only_web_document_root' => 'The only web document root',
    'bin' => 'core/bin/',
    'installation_health_checks_packaging_and_updates' => 'Installation, health checks, packaging, and updates',
    'dist' => '.dist/',
    'release_zips_and_checksum_sidecars' => 'Generated release ZIPs and checksums; ignored by Git',
    'tests' => 'core/tests/',
    'dependency_free_integration_tests' => 'Dependency-free integration tests',
    'docs' => 'core/docs/',
    'architecture_deployment_and_contributor_guidance' => 'Architecture, deployment, and contributor guidance',
    'the_sqlite_provider_implements_storage_settings_and' => 'The SQLite provider implements storage, settings, pages, and optional Entities CRUD. Plugins declare typed entities and use shared create/read/list/update/delete operations after running php core/bin/console.php entities:install. See core/docs/entities.md and site/plugins/catalog/ for examples. Feature plugins use interfaces, never provider-specific SQL. MariaDB and PostgreSQL adapters will need their own queries, migrations, and data-transfer tooling.',
    '04_choose_explicitly' => '04 / CHOOSE EXPLICITLY',
    'configuration_before_connection' => 'Configuration before connection.',
    'copy_2' => 'Copy',
    'config_example_php' => 'config/example.php',
    'to' => 'to',
    'config_local_php' => 'config/local.php',
    'keep_the_local_file_private_select_providers' => '. Keep the local file private. Select providers and enabled feature plugins here, before database access.',
    'providers_storage_sqlite_mail_null_plugins_field' => '\'providers\' => [\'storage\' => \'sqlite\', \'mail\' => null],
\'plugins\' => [\'field-notes\', \'release-download\'],
\'sqlite\' => [\'path\' => \'storage/site.sqlite\'],',
    'select' => 'Select',
    'mail_smtp' => '\'mail\' => \'smtp\'',
    'and_fill_in_the_smtp_configuration_to' => 'and fill in the SMTP configuration to enable bundled PHPMailer. The provider requires TLS and sends plain-text messages. Mail is disabled by default; there is no public form or automatic email.',
    'sqlite_belongs_on_local_disk_with_modest' => 'SQLite belongs on local disk with modest write concurrency. Keep the database and update backups outside the document root.',
    '05_your_expression' => '05 / YOUR EXPRESSION',
    'change_the_surface' => 'Change the surface.',
    'duplicate' => 'Duplicate',
    'themes_studio' => 'site/themes/studio/',
    'choose_a_lowercase_directory_id_and_update' => ', choose a lowercase directory ID, and update',
    'theme_json' => 'theme.json',
    'keep_api_version_1_and_provide' => '. Keep API version 1 and provide',
    'layout_php' => 'layout.php',
    'plus_the_templates_referenced_by' => 'plus the templates referenced by',
    'site_pages_php' => 'site/pages.php',
    'the_shared_layout_wraps_every_page_edit' => '. The shared layout wraps every page. Edit wording in',
    'site_content' => 'site/content/',
    'page_titles_in' => ', page titles in',
    'and_identity_in' => ', and identity in',
    'site_meta_php' => 'site/meta.php',
    'theme_files_own_markup_and_styles' => '; theme files own markup and styles.',
    'php_bin_console_php_theme_your_theme' => 'php core/bin/console.php theme your-theme',
    'the_active_theme_is_stored_by_the' => 'The active theme is stored by the settings service. Assets are served only from the selected theme’s',
    'assets' => 'assets/',
    'folder_through_a_constrained_route_scope_css' => 'folder through a constrained route. Scope CSS under a theme class, escape strings with',
    'e' => 'e()',
    'and_keep_javascript_progressively_enhanced' => ', and keep JavaScript progressively enhanced.',
    'php_themes_and_plugins_execute_trusted_code' => 'PHP themes and plugins execute trusted code. Review them before installing; they are not sandboxed.',
    '06_explicit_connections' => '06 / EXPLICIT CONNECTIONS',
    'add_capabilities_cleanly' => 'Add capabilities, cleanly.',
    'every_plugin_declares_its_id_semantic_version' => 'Custom plugins live in site/plugins/; bundled providers live in core/plugins/. IDs must be unique across both directories. Every plugin declares its ID, semantic version, API, and dependencies in',
    'plugin_json' => 'plugin.json',
    'the_entry_file_returns_an_object_implementing' => '. The entry file returns an object implementing',
    'webspine_contracts_plugin' => 'Webspine\\Contracts\\Plugin',
    'id_my_feature_version_0_1_0' => '{
  "id": "my-feature", "version": "0.1.0", "api": 1,
  "dependencies": {"field-notes": "0.1.0"}
}',
    'public_function_register_app_app_void_pages' => 'public function register(App $app): void {
    $pages = $app->services->get(Pages::class);
    $app->router->get(\'/hello\', function () use ($pages, $app) {
        $page = $pages->find(\'hello\');
        return $app->theme->render(\'page\', [
            \'title\' => $page[\'title\'], \'body\' => $page[\'body\'],
        ]);
    });
}',
    'the_registry_accepts_implementations_of_declared_interfaces' => 'The registry accepts implementations of declared interfaces and rejects duplicate registrations. Providers register services; feature plugins consume them. Providers must be selected in private configuration rather than loaded implicitly as dependencies.',
    'href_field_notes' => '/field-notes',
    'visit_the_working_example_plugin' => 'Visit the working example plugin ↗',
    '07_preserve_what_you_make' => '07 / PRESERVE WHAT YOU MAKE',
    'move_the_core_forward' => 'Move the core forward.',
    'core_releases_carry_an_exact_file_inventory' => 'Core releases carry an exact file inventory with SHA-256 hashes, version, PHP minimum, and API compatibility. Updates validate and stage the archive, check compatibility and health, then activate under an exclusive lock. Failed health checks roll back changed files. A persistent recovery journal blocks requests after an interrupted activation until recovery.',
    'php_bin_console_php_package_php_bin' => 'php core/bin/console.php package
php core/bin/console.php update /path/to/core-release.zip
php core/bin/console.php rollback
php core/bin/console.php recover',
    'site_files_themes_plugins_config_and_data' => 'Site files, themes, custom plugins, config, and data are preserved. Bundled providers in core/plugins/ update with the framework. Create your website from a bootstrap once; use core release archives for framework updates. Pulling or copying the upstream repository over a customized site does not provide this preservation guarantee. Core updates do not migrate databases. Back up the site separately before upgrading. Drain production workers and reset OPcache after activation.',
    'hashes_detect_corruption_they_do_not_authenticate' => 'Hashes detect corruption; they do not authenticate a release. Only apply local archives from a source you trust. Signed online updates and separate extension updates are planned.',
    '08_out_in_the_world' => '08 / OUT IN THE WORLD',
    'give_the_public_one_doorway' => 'Give the public one doorway.',
    'set_your_apache_or_nginx_document_root' => 'Set your Apache or nginx document root to',
    'route_requests_to' => '. Route requests to',
    'index_php' => 'index.php',
    'the_included_apache_configuration_requires' => '; the included Apache configuration requires',
    'mod_rewrite' => 'mod_rewrite',
    'and_override_permissions_disable_directory_indexes_and' => 'and override permissions. Disable directory indexes and deny arbitrary PHP files. See',
    'docs_deployment_md' => 'core/docs/deployment.md',
    'for_an_nginx_example' => 'for an nginx example.',
    'the_php_worker_needs_read_access_to' => 'The PHP worker needs read access to framework and extensions, and write access to',
    'only_the_operator_performing_an_update_needs' => '. Only the operator performing an update needs write access to framework files. Use HTTPS, back up data, and keep',
    'out_of_version_control' => 'out of version control.',
    'for_a_bootstrap_zip_including_the_starter' => 'For a bootstrap ZIP including the starter theme and providers, run',
    'php_bin_console_php_package_full' => 'php core/bin/console.php package --full',
    'a_normal_core_release_contains_only_managed' => '. A normal core release contains only managed framework files.',
    '09_do_the_boring_things_well' => '09 / DO THE BORING THINGS WELL',
    'solid_underneath' => 'Solid underneath.',
    'templates_escape_untrusted_output_sqlite_queries_are' => 'Templates escape untrusted output. SQLite queries are parameterized. Asset routes are confined to the selected theme and approved file types. The starter theme includes keyboard navigation, visible focus, reduced-motion support, responsive layouts, and accessible tabs.',
    'php_tests_run_php' => 'php core/tests/run.php',
    'integration_checks_cover_installation_persistence_provider_subst' => 'Integration checks cover installation, persistence, provider substitution, routing, escaping, extension contracts, archive integrity, preservation, and rollback. WCAG 2.2 AA is the target; a full assistive-technology audit remains to be done.',
    'before_adding_mutation_endpoints_implement_authentication_author' => 'Before adding mutation endpoints, implement authentication, authorization, input validation, and CSRF protection. This bootstrap has no admin editor, uploads, or public mutation forms.',
    '10_the_state_of_the_spine' => '10 / THE STATE OF THE SPINE',
    'here_today_next_tomorrow' => 'Here today. Next tomorrow.',
    'built' => 'Built',
    'routing_and_responses_registry_plugin_contracts_action' => 'Routing and responses; registry, plugin contracts, action hooks; SQLite settings and pages; explicit idempotent installation and schema recording; theme selection and protected assets; optional SMTP with PHPMailer; installation, health, packaging, and reversible local core updates; integration tests.',
    'planned' => 'Planned',
    'mariadb_postgresql_adapters_and_data_transfer_independent' => 'MariaDB / PostgreSQL adapters and data transfer; independent plugin and provider updates; signed online updates, potentially operated by AI; admin and content editing; authentication; public forms and uploads.',
    'version_0_1_0_is_an_implemented' => 'Version 0.1.0 provides the foundation for building and maintaining your own website with AI.',
];
