<?php
declare(strict_types=1);

// Plain text only. The theme escapes every value when rendering.
return [
    'headline_line_1' => 'Your own',
    'headline_line_2' => 'AI-driven',
    'headline_line_3' => 'website',
    'hero_description' => 'Build and maintain your own website with AI.',
    'hero_ownership' => 'Your code. Your ideas. Your choice of AI.',
    'href_docs_quickstart' => '/docs#quickstart',
    'start_building' => 'Start building',
    'href_architecture' => '#architecture',
    'explore_the_framework' => 'Explore the framework',
    'symbol' => '</>',
    'plain_code_no_build_step_entirely_yours' => 'Plain code. No build step. Entirely yours.',
    'aria_label_illustration_of_a_website_built_from_an' => 'Illustration of a website built from an independent theme, plugins, and a stable core',
    'fig_01_the_anatomy_of_a_website' => 'FIG. 01   /   THE ANATOMY OF A WEBSITE',
    'your_expression' => 'your expression',
    'themes' => 'themes',
    'your_possibilities' => 'your possibilities',
    'plugins' => 'plugins',
    'your_foundation' => 'your foundation',
    'core' => 'core',
    'make_it_yours' => 'make it yours',
    'solid_underneath' => 'solid underneath',
    'separate_by_design_connected_by_contract' => 'SEPARATE BY DESIGN. CONNECTED BY CONTRACT.',
    'a_familiar_stack' => 'A familiar stack.',
    'a_fresh_starting_point' => 'A fresh starting point.',
    'html' => 'HTML',
    'css' => 'CSS',
    'javascript' => 'JavaScript',
    'php' => 'PHP',
    'sqlite' => 'SQLite',
    'no_npm' => 'No npm.',
    'no_composer' => 'No Composer.',
    'the_idea' => '/ THE IDEA',
    'less_machinery' => 'Less machinery.',
    'more' => 'More',
    'making' => 'making.',
    'your_website_your_ai_your_way' => 'Your website. Your AI. Your way.',
    'is_a_small_readable_foundation_designed_for' => 'is a lean, open-source foundation for building and maintaining your website with your choice of AI. Clear boundaries between content, themes, components, and plugins give your AI guardrails to keep the code organized and maintainable.',
    'use_your_own_ai_app_with_access' => 'Bring your own AI app with access to your project files—such as ChatGPT Desktop, Claude Code, or OpenCode. You own the code and can keep developing it independently of future webspine releases.',
    'simple_hosting' => 'Built with plain PHP, HTML, CSS, and JavaScript. No frontend framework, Node.js runtime, or build step—just straightforward deployment on a PHP web server with SQLite support.',
    'href_docs_principles' => '/docs#principles',
    'meet_the_principles' => 'Meet the principles',
    'code_your_ai_can_follow' => 'Code your AI can follow.',
    'plain_php_and_browser_native_code_clear' => 'Plain PHP and browser-native code. Clear structure helps your AI understand the project and make focused changes.',
    'your_site_stays_yours' => 'Your site stays yours.',
    'themes_plugins_and_content_live_outside_the' => 'Themes, plugins, and content live outside the core. Update the foundation, keep your identity.',
    'small_with_room_to_grow' => 'Small enough to make your own.',
    'explicit_service_contracts_add_a_provider_or' => 'A lean, readable foundation you and your AI can maintain and extend—without relying on future webspine releases. You own the code and its direction.',
    'the_structure' => '/ THE STRUCTURE',
    'everything_in' => 'Everything in',
    'its_own_place' => 'its own place.',
    'a_stable_core_an_independent_surface' => 'A stable core. An independent surface.',
    'a_clear_connection_between_the_two' => 'A clear connection between the two.',
    'aria_label_framework_layers' => 'Framework layers',
    'themes_2' => 'Themes',
    'the_look_the_feel_the_you' => 'The look. The feel. The you.',
    'plugins_2' => 'Plugins',
    'capabilities_on_your_terms' => 'Capabilities, on your terms.',
    'core_2' => 'Core',
    'the_dependable_backbone' => 'The dependable backbone.',
    'themes_your_theme' => 'site / themes / your-theme /',
    'your_design_in_familiar_files' => '// Your design, in familiar files.',
    'themes_your_theme_2' => 'site/themes/
  your-theme/',
    'theme_json' => 'theme.json',
    'identity_api' => '← identity & API',
    'layout_php' => 'layout.php',
    'shared_structure' => '← shared structure',
    'home_php_assets_style_css_app_js' => 'home.php
    assets/
      style.css
      app.js',
    'design_without_asking_the_core_for_permission' => 'Design without asking the core for permission.',
    'plugins_field_notes' => 'site / plugins / field-notes /',
    'small_extensions_explicit_connections' => '// Small extensions. Explicit connections.',
    'plugins_sqlite' => 'core/plugins/
  sqlite/',
    'storage_provider' => '← storage provider',
    'smtp' => 'smtp/',
    'mail_provider' => '← mail provider',
    'field_notes' => 'site/plugins/field-notes/',
    'plugin_json' => 'plugin.json',
    'dependencies' => '← dependencies',
    'plugin_php' => 'plugin.php',
    'routes_hooks' => '← routes & hooks',
    'app_services_get_pages_class' => '$app->services->get(Pages::class);',
    'consume_a_contract_choose_your_provider' => 'Consume a contract. Choose your provider.',
    'core_src' => 'core / src /',
    'just_enough_to_hold_it_all_together' => '// Just enough to hold it all together.',
    'core_bootstrap_php_src' => 'core/
  bootstrap.php
  src/',
    'contracts' => 'Contracts/',
    'service_interfaces' => '← service interfaces',
    'router_php_registry_php_theme_php_updater' => 'Router.php
    Registry.php
    Theme.php
    Updater.php',
    'update_the_core_preserve_everything_around_it' => 'Update the core. Preserve everything around it.',
    'separate_folders_shared_contracts' => 'Separate folders. Shared contracts.',
    'no_tangled_dependencies' => 'No tangled dependencies.',
    'href_docs_architecture' => '/docs#architecture',
    'explore_the_architecture' => 'Explore the architecture',
    'your_next_website' => '/ YOUR NEXT WEBSITE',
    'from_zero' => 'From zero',
    'to' => 'to',
    'your_thing' => 'your thing.',
    'download_install_start_making' => 'Download. Install. Start making.',
    'there_s_no_toolchain_to_get_in' => 'There’s no toolchain to get in your way.',
    'href_download' => '/download',
    'get' => 'Get',
    'v' => 'v',
    'mit_license_zip_download' => '· MIT license · ZIP download',
    'your_terminal' => 'Your terminal',
    'aria_label_copy_installation_commands' => 'Copy installation commands',
    'copy' => 'Copy',
    'in_your_extracted_webspine_folder' => '# In your extracted webspine folder',
    'php_bin_console_php_install' => 'php core/bin/console.php install',
    'start_your_local_development_server' => '# Start your local development server',
    'php_s_localhost_8080_t_public_public' => 'php -S localhost:8080 -t public public/router.php',
    'open_localhost_8080_make_something_good' => 'Open localhost:8080. Make something good.',
    'honestly_where_we_are' => '/ HONESTLY, WHERE WE ARE',
    'the_bootstrap_not_a_complete_cms' => 'THE BOOTSTRAP, NOT A COMPLETE CMS',
    'a_foundation' => 'A foundation,',
    'with_a_future' => 'with a future.',
    'the_essentials_are_here_routing_sqlite_persistence' => 'The essentials are here: routing, SQLite persistence, themes, plugins, SMTP, and reversible local core updates.',
    'content_editing_authentication_more_database_providers_and' => 'Content editing, authentication, more database providers, and signed online updates are still ahead. This is a starting point you can understand and build on.',
    'href_docs_roadmap' => '/docs#roadmap',
    'see_what_s_here_what_s_next' => 'See what’s here & what’s next',
    'good_websites' => 'Good websites',
    'start_with_a' => 'start with a',
    'solid_spine' => 'solid spine.',
    'build_your_next_idea' => 'Build your next idea',
];
