<?php
declare(strict_types=1);
$escape=static fn(mixed $v):string=>e((string)$v);
$labels=['browser'=>'Browser-like · likely humans','ai-training'=>'AI training crawlers','ai-search'=>'AI search crawlers','ai-user'=>'AI user-triggered fetches','search-bot'=>'Search-engine bots','other-bot'=>'Other automation','unknown'=>'Unknown'];
$ai=$report['kinds']['ai-training']+$report['kinds']['ai-search']+$report['kinds']['ai-user'];
$bots=$report['kinds']['search-bot']+$report['kinds']['other-bot'];
$max=max(1,...array_values($report['daily']));

?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>spineanalytics</title><style><?= $reportCss ?? str_replace([chr(13).chr(10),chr(13)],chr(10),file_get_contents(__DIR__.'/assets/report.css')) ?></style></head><body>
<main class="insights-shell"><header><span class="insights-brand">spine<strong>analytics</strong><span>✳</span></span><span class="private-badge">PRIVATE INSIGHTS</span></header>
<?php if ($demo): ?><div class="sample-notice">SAMPLE DATA · This is an illustration of the report, not real website traffic.</div><?php elseif (isset($app) && ($preview??false)): ?><div class="sample-notice">LOCAL PREVIEW · These counts come from local preview requests. <a href="/_insights?demo=1">View sample report ↗</a></div><?php endif; ?>
<div class="report-heading"><div><p class="eyebrow">A LITTLE SIGNAL. NO BIG TRACKING.</p><h1>Who’s stopping by?</h1><p>Request trends without following people around.</p></div><div class="period"><span><?= $escape($report['start']) ?> — <?= $escape($report['end']) ?> · UTC</span><?php if (isset($app)): ?><nav aria-label="Report period"><?php foreach ([7,30,90] as $days): ?><a <?= $report['days']===$days?'aria-current="page"':'' ?> href="/_insights?days=<?= $days ?><?= $demo?'&amp;demo=1':'' ?>"><?= $days ?> days</a><?php endforeach; ?></nav><?php endif; ?></div></div>
<div class="stat-grid"><?php foreach ([['Counted requests',$report['requests'],'Application requests, excluding assets and health checks'],['Browser-like',$report['kinds']['browser'],'Likely human traffic · not verified'],['AI agents',$ai,'Training, search and user-triggered fetches'],['Other bots',$bots,'Search engines and other automation']] as [$label,$value,$detail]): ?><section class="stat"><h2><?= $escape($label) ?></h2><strong><?= number_format($value) ?></strong><p><?= $escape($detail) ?></p></section><?php endforeach; ?></div>
<section class="insights-card"><div class="card-heading"><h2>Requests over time</h2><span><?= $report['days'] ?> days · daily totals</span></div>
<?php if ($report['requests']===0): ?><p class="empty-state">No counted requests yet. Visit a few pages, then refresh this report.</p><?php endif; ?>
<svg class="trend-chart" viewBox="0 0 900 190" role="img" aria-labelledby="trend-title"><title id="trend-title">Daily counted requests from <?= $escape($report['start']) ?> to <?= $escape($report['end']) ?></title><line x1="0" x2="900" y1="175" y2="175" class="chart-axis"/><?php $i=0;$step=900/count($report['daily']);foreach ($report['daily'] as $day=>$n): $height=$n>0?max(2,150*$n/$max):0;?><rect x="<?= round($i*$step+3,2) ?>" y="<?= round(175-$height,2) ?>" width="<?= max(2,round($step-6,2)) ?>" height="<?= round($height,2) ?>" rx="3" class="chart-bar"><title><?= $escape($day) ?>: <?= $n ?> requests</title></rect><?php $i++;endforeach; ?></svg><div class="chart-labels"><span><?= $escape($report['start']) ?></span><span>Peak: <?= number_format(max($report['daily'])) ?> requests / day</span><span><?= $escape($report['end']) ?></span></div></section>
<div class="detail-grid"><section class="insights-card"><div class="card-heading"><h2>Traffic mix</h2><span>Best-effort estimates</span></div><ul class="metric-list"><?php foreach ($labels as $kind=>$label): $value=$report['kinds'][$kind]; ?><li><span><?= $escape($label) ?></span><strong><?= number_format($value) ?></strong><small><?= $report['requests']?round(100*$value/$report['requests'],1):0 ?>%</small></li><?php endforeach; ?></ul></section><section class="insights-card"><div class="card-heading"><h2>Popular pages</h2><span>Counted requests</span></div><ul class="metric-list"><?php foreach (array_slice($report['pages'],0,8,true) as $page=>$n): ?><li><code><?= $escape($page) ?></code><strong><?= number_format($n) ?></strong></li><?php endforeach; ?></ul><?php if (!$report['pages']): ?><p class="empty-state">Your pages will appear here.</p><?php endif; ?></section></div>
<section class="insights-card"><div class="card-heading"><h2>Browser &amp; device totals</h2><span>Separate daily aggregates</span></div><p>Derived only from User-Agent headers on browser-like requests. Each category is counted independently: no links to pages, bots, or other device categories. No raw headers are saved.</p><div class="header-grid"><?php foreach (['browser'=>'Browsers','os'=>'Operating systems','device'=>'Device categories'] as $dimension=>$label): ?><section><h3><?= $escape($label) ?></h3><ul class="metric-list"><?php foreach (($report['headers'][$dimension]??[]) as $value=>$n): ?><li><span><?= $escape($value) ?></span><strong><?= number_format($n) ?></strong></li><?php endforeach; ?></ul><?php if (empty($report['headers'][$dimension])): ?><p class="empty-state">No totals recorded in this period.</p><?php endif; ?></section><?php endforeach; ?></div><p>These are request estimates, not unique devices. Reduced or disguised headers can produce unknown or incorrect categories; versions, device models and locations are not collected.</p></section>
<div class="detail-grid"><section class="insights-card"><div class="card-heading"><h2>Recognised agents</h2><span>Names claimed by clients</span></div><ul class="metric-list"><?php foreach ($report['agents'] as $name=>$n): ?><li><span><?= $escape($name) ?></span><strong><?= number_format($n) ?></strong></li><?php endforeach; ?></ul></section><section class="insights-card"><div class="card-heading"><h2>How to read this</h2><span>No visitor profiles</span></div><p><strong><?= number_format($report['page_requests']) ?></strong> successful page GETs · <strong><?= number_format($report['errors']) ?></strong> requests returned a 4xx or 5xx status.</p><p>These are requests, not unique visitors. Browsers can prefetch pages, bots can disguise themselves, and agent names can be spoofed. AI fetches requested by a person are separated from automatic crawlers.</p><p>Only requests that reach the PHP application are counted. Cached responses and files served directly by the web server may not appear.</p></section></div>
<footer><strong>Small on purpose.</strong><p>No cookies, pixels, IP storage, raw user-agent strings, referrers, query strings or visitor identifiers. Daily totals expire after 90 days on the next counted request. Unknown URLs are combined into [other].</p></footer></main></body></html>
