<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <ProjectReference Include="../Webspine.Content.Sqlite/Webspine.Content.Sqlite.csproj" />
    <ProjectReference Include="../Webspine.Caching.Memory/Webspine.Caching.Memory.csproj" />
    <ProjectReference Include="../Webspine.Demo/Webspine.Demo.csproj" />
  </ItemGroup>
</Project>
