<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../src/Webspine.Core/Webspine.Core.csproj" />
    <EmbeddedResource Include="Design/*" LogicalName="design/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
